### PR TITLE
binlog.json: add queue size and query histogram

### PR DESCRIPTION
**Pull request by july2993**
merge after https://github.com/pingcap/tidb-binlog/pull/394 and https://github.com/pingcap/tidb-binlog/pull/393

### CODE REVIEW

**Comment by july2993** [comment]
@GregoryIan @WangXiangUSTC @liubo0127 PTAL

**Comment by july2993** [comment]
2018-11-16 4 29 07 pm
2018-11-16 4 28 59 pm

**Comment by GregoryIan** [comment]
LGTM @july2993 is best guy

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
