### PR TITLE
Add tidb skip binlog count graph in tidb and binlog dashboards

### PR DESCRIPTION
**Pull request by aylei**
Preview:
TiDB:
image
Binlog:
image

Signed-off-by: Aylei <rayingecho@gmail.com>

### CODE REVIEW

**Comment by aylei** [comment]
@july2993 @liubo0127 @lamxTyler @GregoryIan PTAL

**Comment by july2993** [comment]
I think you should only add in tidb's dashboard.

**Comment by aylei** [comment]
One possible case is that there are only part of tidb-servers stop writing binlog, user cannot distinguish this from the binlog dashboard if we don't have this graph.
@july2993

**Comment by aylei** [comment]
@july2993 From the technical perspective, yes. But from the user side (when I wa a user myself), I think this makes the binlog status clearer.
Having said that, I'm okay about only adding the graph in the TiDB dashboard. @GregoryIan How do you think?

**Comment by aylei** [comment]
> LGTM for the critical and binlog part
> but this pr also a `tidb_server_handshake_error_total` ?

I don't know why this is included, I just load the latest json and add a graph about `tidb_server_critical_error`

**Comment by aylei** [comment]
@july2993 I see, it is an issue of the diff algorithm of github, it thought the `handshake_error_total` is changed to `critical_error_total`, and a new graph `handshake_error_total` is added, which is misleading.  But the final result is as we expected.

**Comment by aylei** [comment]
@july2993 Could you please take a look again?

**Comment by aylei** [comment]
@lamxTyler @july2993 Could you please approve this PR?

**Pull request merged**
