### PR TITLE
add alert rule for tidb binlog error count

### PR DESCRIPTION
**Pull request by imtbkcat**
Rename a TiDB metrics counter from `critical_error_total` to `binlog_error_total` and add alert rule for it.

### CODE REVIEW

**Comment by ericsyh** [comment]
@jackysp @imtbkcat 
Change the alert rule to use `critical_error_tota` and update the dashbaord name from `Uncommon Error OPM` to `Write Binlog Error`. 
PTAL.

**Comment by jackysp** [comment]
Have you ever test if the alert rule works?

**Comment by imtbkcat** [comment]
@jackysp i will make a test

**Comment by jackysp** [comment]
Any update? @imtbkcat

**Comment by liubo0127** [comment]
LGTM

**Comment by imtbkcat** [comment]
@jackysp There's some problems after test, i will fix it.

**Comment by imtbkcat** [comment]
PTAL @jackysp

**Pull request merged**
