### PR TITLE
scripts: update DDL metrics

### PR DESCRIPTION
**Pull request by zimulala**
Add job action and schema version information to DDL metrics.

Merge after pingcap/tidb#7472

screen shot 2018-08-28 at 10 46 37
screen shot 2018-08-28 at 10 46 46

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @tiancaiamao @coocood

**Comment by shenli** [comment]
Could you post the screenshot here?

**Comment by zimulala** [comment]
@shenli Done.

**Comment by tiancaiamao** [comment]
version as label? will it generate too much of labels and difficult to show in the grafana ?

**Comment by tiancaiamao** [comment]
LGTM @winkyao

**Comment by coocood** [comment]
LGTM

**Pull request merged**
