### PR TITLE
scripts: hide tombstone store

### PR DESCRIPTION
**Pull request by rleungx**
This PR is going to hide the store whose status is tombstone.

### CODE REVIEW

**Comment by LinuxGit** [comment]
@rleungx Does it need to cherry pick to release-2.1 ?
https://github.com/pingcap/tidb-ansible/tree/release-2.1

**Comment by rleungx** [comment]
@LinuxGit Sorry for delay, it's not necessary for now.

**Comment by rleungx** [comment]
@LinuxGit Hi, PD has released v2.1.0-rc.4 which cherry pick pingcap/pd#1289. So this PR also need to cherry pick now.

**Comment by LinuxGit** [comment]
@rleungx done

**Pull request merged**
