### PR TITLE
scripts: add some metrics for tidb

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
This script shows what it looks like http://172.16.5.34:34125/d/000000011/test-cluster-tidb?orgId=1&from=now-1h&to=now&refresh=30s

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Do we have slow_query related metrics? @jackysp

**Comment by jackysp** [comment]
Yes, already have one.

**Comment by jackysp** [comment]
> how about add
> 
> * `process_open_fds` identify socket fd problem(mainly to tikv side connection increase)
good idea
> * `go_memstats_gc_cpu_fraction` percent between 0 to 1
ok
> * `go_memstats_heap_inuse` maybe need change to `go_memstats_heap_alloc_bytes`? https://golang.org/pkg/runtime/#MemStats(maybe we can copy comments to metric's description)
ok, but I firstly do not want to change the existed formula.
> * `sum(tidb_tikvclient_pending_batch_requests) by (instance)` => `sum(tidb_tikvclient_pending_batch_requests) by (store)`
ok, but I'm afraid the num of tikv will be so many.
> * maybe we need add `tidb_tikvclient_lock_cleanup_task_total`  and `tidb_tikvclient_range_task_stats` with its labels?
They're already there.

**Comment by jackysp** [comment]
PTAL @lysu

**Comment by lysu** [comment]
LGTM

**Pull request merged**
