### PR TITLE
scripts: more metrics for lock manager

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

Update metrics about lock manager:
image
image

### CODE REVIEW

**Comment by liubo0127** [comment]
LGTM

**Comment by youjiali1995** [comment]
@liubo0127 It can be merged.

**Comment by liubo0127** [comment]
@shafreeck PTAL

**Comment by youjiali1995** [comment]
@liubo0127 Can we merge it? It should be taken into v3.0.9.

**Comment by youjiali1995** [comment]
@MyonKeminta @sticnarf PTAL

**Pull request merged**
