### PR TITLE
script: statistics region size  and keys in a table

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve? 

Add a new script to statistics region size and keys in a table, it will output by group, which splited by empty region, max-merge-region-size, standard region and max region size default. Of course, it is also enable to be splited by specified size.

```
usage: test.py [-h] [--host HOST] [-d] [--port PORT] [--pd_host PD_HOST]
               [--pd_port PD_PORT] [--group GROUP]
               database table

Show region size and keys distribution of a TiDB table.

positional arguments:
  database           database name
  table              table name

optional arguments:
  -h, --help         show this help message and exit
  --host HOST        tidb-server address, default: 127.0.0.1
  -d                 whether to draw pictures, default: False
  --port PORT        tidb-server status port, default: 10080
  --pd_host PD_HOST  pd-server address, default: 127.0.0.1
  --pd_port PD_PORT  pd-server status port, default: 2379
  --group GROUP      the result group num, default: 0 (split by default mode)
```

### Input example:

` python table_regions_size.py --host 127.0.0.1 --port 30726 --pd_host 127.0.0.1 --pd_port 2379 test usertable`

### Output example:
```
Region keys		Region num
0 ~ 20k         	76
20k ~ 200k      	16652
200k ~ 960k     	323
960k ~ 2214k    	437

Region size		Region num
0 ~ 2           	0
2 ~ 20          	0
20 ~ 96         	8800
96 ~ 189        	8688

```
#### Picture
If you have installed matplotlib, it also output pictures ordered by region id.

image
image

### CODE REVIEW

**Comment by rleungx** [comment]
I think we can also support the key statistics

**Comment by lhy1024** [comment]
> I think we can also support the key statistics

It just has been supported.

**Comment by nolouch** [comment]
Do we need to add `requirements.txt`?

**Comment by lhy1024** [comment]
> Do we need to add `requirements.txt`?

I'm not sure whether it is necessary to draw a picture. If necessary, then need to append `requirement`.

**Comment by lhy1024** [comment]
PTAL @rleungx

**Comment by rleungx** [comment]
We can make an option to draw a picture.

**Comment by lhy1024** [comment]
> We can make an option to draw a picture.

done. PTAL @rleungx

**Pull request merged**
