### PR TITLE
scripts: templating job labels

### PR DESCRIPTION
**Pull request by overvenus**
So we can monitor single tikv instance.

image

image

### CODE REVIEW

**Comment by overvenus** [comment]
@huachaohuang Yes, now we can pick a instance on the TiKV dashboard.

**Comment by huachaohuang** [comment]
Awesome, this PR doesn't seem reviewable so I just trust you, LGTM.

**Comment by overvenus** [comment]
It's actually very simple, attach `{job=~\"$job\"}` to every metrics expr.

**Comment by overvenus** [comment]
@LinuxGit PTAL

**Pull request merged**
